### ISSUE TITLE
GRBL Control Tab greyed out 

### ISSUE THREAD

**Issue by thommy884** [synman/Octoprint-Bettergrblsupport#81] opened 2022-03-21 18:29 UTC
Hi there. I'm able to connect to my CNC3018pro (baudrate 115200, board with GRBL 0.8) but the grbl control tab is greyed out. If | use the normal control tab of octoprint, I can jog. I can turn on and off the spindle via terminal as well. Do u guys have an idea what I could try? Pls see the attached screenshot and octoprint logs, thanks a lot! 
![image](https://user-images.githubusercontent.com/92954914/159338012-decc407b-312d-4593-8fec-1cb1b73a750f.png)

[octoprint-systeminfo-20220321192109.zip](https://github.com/synman/Octoprint-Bettergrblsupport/files/8318291/octoprint-systeminfo-20220321192109.zip)

**Comment by synman** [comment] 2022-03-21 19:03
Id like to see your terminal window.  Notice how state is N/A?

**Comment by thommy884** [comment] 2022-03-21 19:27
hi. wow, you are fast! yeah, I noticed that. Not much to see in the terminal (see attached).

![image](https://user-images.githubusercontent.com/92954914/159349108-56e64c43-913b-4af5-a5d2-b2d072463023.png)

**Comment by thommy884** [comment] 2022-03-21 19:30
but when I jog via the ordinary control tab, then it looks like that:

![image](https://user-images.githubusercontent.com/92954914/159349592-df823947-e808-42c5-a452-9a4a579ca587.png)

**Comment by synman** [comment] 2022-03-22 01:07
The built in control tab is not supported and it's dumb luck it is working at all.  Please share your terminal window contents when attempting to connect.

I may find it in the state files you shared but yeah it would be a lot easier to just see what is being sent back and forth between Octoprint and your machine.

**Comment by synman** [comment] 2022-03-22 01:09
> hi. wow, you are fast! yeah, I noticed that. Not much to see in the terminal (see attached).
> 
> ![image](https://user-images.githubusercontent.com/92954914/159349108-56e64c43-913b-4af5-a5d2-b2d072463023.png)
> 

Do you mind sharing what machine it is you are trying to control.  I'm guessing this is not a GRBL machine... Possibly Marlin.

**Comment by thommy884** [comment] 2022-03-22 07:23
> mind

Sure, it is this machine: https://de.aliexpress.com/item/4000096760805.html?gatewayAdapt=glo2deu&spm=a2g0o.order_list.0.0.21ef5c5f12hAcZ

This is a CNC 3018 Pro GRBL Control CNC Maschine. It works with ChiliPeppr, CNCjs or Candle. I already tested that. But Better GRBL Support would be the ideal choice for me because it is webbased, has a built in webcam support and so many plugins. 

This is shown in the terminal when I disconnect and reconnect to the CNC:

![image](https://user-images.githubusercontent.com/92954914/159428661-427a209a-c37e-41dc-bea2-3ec4f8275d50.png)

**Comment by synman** [comment] 2022-03-22 12:56
Ah... Grbl v.9

Status reporting is disabled.

Take a look at $10 ... You'll want to set it to 3.

$10=3

Report back results.

**Comment by synman** [comment] 2022-03-22 12:58
Grbl v.9 documentation is here:. https://github.com/grbl/grbl/wiki/Configuring-Grbl-v0.9#grbl-settings

**Comment by thommy884** [comment] 2022-03-22 14:34
Ok, so I changed $10 to 3 and this is what the terminal shows now:

![image](https://user-images.githubusercontent.com/92954914/159506277-62caf088-0a49-4e81-a896-fff4166573be.png)
![image](https://user-images.githubusercontent.com/92954914/159506398-445679bf-16ee-4ff2-8eb4-035edd225c08.png)

**Comment by thommy884** [comment] 2022-03-22 21:36
So I restarted octoprint and the whole pi. The only thing that works within the grbl control tab is the home button (only when I previously jog via built-in control tab). I think I'll give a firmware update a try...but it is a no name board without any type of brand/indication. Should I just try to upload a firmware meant for a genmitsu 3018 pro? Or could I brick the controller in that case? Gonna do some research now. Any other suggestions? Thanks again!

**Comment by synman** [comment] 2022-03-22 23:08
do you mind sharing what your GRBL Control tab looks like now that we have $10 set to 3?   I just took a quick look at the code and if signature is empty, it should default to GRBL .9 jogging.

I'd also like you to hit the direction buttons a couple times, toggle over to the terminal window afterwards and show me what is getting logged there.

**Comment by thommy884** [comment] 2022-03-23 20:17
this is the GRBL control tab now: it is complaining all the time that "distance exceeds x axis". It's the same for y and z axis:

![image](https://user-images.githubusercontent.com/92954914/159787648-53f97f5d-16d3-475f-b6c4-9a0818cf02cf.png)

this is what the terminal looks like when I press the right  button on x axis:

![image](https://user-images.githubusercontent.com/92954914/159787938-1b025e0b-6bab-413c-9d68-5e991edb1082.png)

**Comment by thommy884** [comment] 2022-03-23 21:55
Just updated to 1.1 and now i can jog, thank u so much! how can I test the spindle? M03 does not work...great plugin anyway!

**Comment by synman** [comment] 2022-11-04 21:41
M3S####

with #### being some number within your min and max spindle speed settings.

I'm closing the issue.   Fill free to open a discussion thread if you would like to discuss this further (aka not a bug :) )

**Closed by synman** 2022-11-04 21:41 UTC
Labels: question
