### ISSUE TITLE
Octoprint GRBL help

### ISSUE THREAD

**Issue by X15AC** [synman/Octoprint-Bettergrblsupport#122] opened 2023-08-03 18:49 UTC
Sorry not sure if this is the correct place to ask for help.
Had it working and it was great, but I had to start over and can't get it to work today.

Great plugin. I had it working however, I had to reload Octoprint and the plug in. I see Better Grbl Support Plugin for Octoprint but it does not save the changes listed in GETHUB. I installed the plugin from plugin manager and rebooted. I have a temp tab also, on the far right a GRBL drop down. I tied your settings for you printer no connection Recv: error:20 grbl. My laser is Aufero 2. Any suggestions?

Thanks in advance. 

[octoprint-systeminfo-20230803115418.zip](https://github.com/synman/Octoprint-Bettergrblsupport/files/12254104/octoprint-systeminfo-20230803115418.zip)

**Comment by synman** [comment] 2023-10-05 02:07
I suspect this is a duplicate of #118 please see that issue for details on how to work-around this

**Closed by synman** 2023-10-05 02:07 UTC
Labels: duplicate
