### ISSUE TITLE
New Update cannot connect to laser

### ISSUE THREAD

**Issue by mbt45** [synman/Octoprint-Bettergrblsupport#75] opened 2022-01-20 18:25 UTC
The new upgrade is not able to connect the the laser  anymore. (Laser engraver Neje).

How can I reverse to the previous version?

"Connected to: Serial<id=0x6a0711f0, open=True>(port='/dev/ttyUSB0', baudrate=115200, bytesize=8, parity='N', stopbits=1, timeout=10.0, xonxoff=False, rtscts=False, dsrdtr=False), starting monitor
Send: M110 N0
No answer from the printer within the connection timeout, trying another hello
Send: M110 N0
There was a timeout while trying to connect to the printer
Changing monitoring state from "Connecting" to "Offline"
Connection closed, closing down monitor"

**Comment by synman** [comment] 2022-01-20 19:15
Please ensure you are on the latest version (2.1.3)

Additionally, if you have verified you are on 2.1.3,  I'm going to need to see your octoprint.log file.   This looks to me like there is an error being thrown and I need to see the stacktrace.

**Comment by synman** [comment] 2022-01-20 19:18
See #69 and #71

**Comment by mbt45** [comment] 2022-01-20 20:28
It is on version 2.1.3

`2022-01-20 20:26:07,019 - octoprint.startup - INFO - ******************************************************************************
2022-01-20 20:26:07,023 - octoprint.startup - INFO - Starting OctoPrint 1.7.2
2022-01-20 20:26:07,024 - octoprint.startup - INFO - ******************************************************************************
2022-01-20 20:26:11,000 - octoprint.util.connectivity.connectivity_checker - INFO - Connectivity changed from offline to online
2022-01-20 20:26:11,001 - octoprint.util.connectivity.connectivity_checker - INFO - Connectivity state is currently: online
2022-01-20 20:26:11,001 - octoprint.util.connectivity.connectivity_checker - INFO - Connecting to 1.1.1.1:53 is working
2022-01-20 20:26:11,002 - octoprint.util.connectivity.connectivity_checker - INFO - Resolving octoprint.org is working
2022-01-20 20:26:11,603 - octoprint.startup - INFO - Blacklist processing done, adding 3 blacklisted plugin versions: roomtemp (any), GcodeEditor (>=0.1.1,<=0.2.8), gcodeleveling (>=0.1.0,<=0.1.1)
2022-01-20 20:26:11,604 - octoprint.plugin.core - WARNING - Invalid version requirement >=0.1.1,<=0.2.8 for blacklist entry GcodeEditor, ignoring
2022-01-20 20:26:11,604 - octoprint.plugin.core - WARNING - Invalid version requirement >=0.1.0,<=0.1.1 for blacklist entry gcodeleveling, ignoring
2022-01-20 20:26:11,687 - octoprint.plugin.core - INFO - Loading plugins from /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins, /home/pi/.octoprint/plugins and installed plugin packages...
2022-01-20 20:26:13,136 - octoprint.plugin.core - INFO - Plugin GCode Viewer is disabled.
2022-01-20 20:26:13,884 - octoprint.plugin.core - INFO - Found 19 plugin(s) providing 18 mixin implementations, 42 hook handlers
2022-01-20 20:26:14,133 - octoprint.server.heartbeat - INFO - Starting server heartbeat, 900.0s interval
2022-01-20 20:26:14,162 - octoprint.server - INFO - Intermediary server started
2022-01-20 20:26:14,193 - octoprint.filemanager.storage - INFO - Initializing the file metadata for /home/pi/.octoprint/uploads...
2022-01-20 20:26:14,247 - octoprint.filemanager.storage - INFO - ... file metadata for /home/pi/.octoprint/uploads initialized successfully.
2022-01-20 20:26:14,252 - octoprint.server - INFO - Added new permission from plugin action_command_notification: PLUGIN_ACTION_COMMAND_NOTIFICATION_SHOW (needs: "Need(method='role', value='plugin_action_command_notification_show')")
2022-01-20 20:26:14,253 - octoprint.server - INFO - Added new permission from plugin action_command_notification: PLUGIN_ACTION_COMMAND_NOTIFICATION_CLEAR (needs: "Need(method='role', value='plugin_action_command_notification_clear')")
2022-01-20 20:26:14,254 - octoprint.server - INFO - Added new permission from plugin action_command_prompt: PLUGIN_ACTION_COMMAND_PROMPT_INTERACT (needs: "Need(method='role', value='plugin_action_command_prompt_interact')")
2022-01-20 20:26:14,254 - octoprint.server - INFO - Added new permission from plugin announcements: PLUGIN_ANNOUNCEMENTS_READ (needs: "Need(method='role', value='plugin_announcements_read')")
2022-01-20 20:26:14,255 - octoprint.server - INFO - Added new permission from plugin announcements: PLUGIN_ANNOUNCEMENTS_MANAGE (needs: "Need(method='role', value='plugin_announcements_manage'), Need(method='role', value='plugin_announcements_read')")
2022-01-20 20:26:14,255 - octoprint.server - INFO - Added new permission from plugin appkeys: PLUGIN_APPKEYS_ADMIN (needs: "Need(method='role', value='plugin_appkeys_admin')")
2022-01-20 20:26:14,255 - octoprint.server - INFO - Added new permission from plugin backup: PLUGIN_BACKUP_ACCESS (needs: "Need(method='role', value='plugin_backup_access')")
2022-01-20 20:26:14,256 - octoprint.server - INFO - Added new permission from plugin firmware_check: PLUGIN_FIRMWARE_CHECK_DISPLAY (needs: "Need(method='role', value='plugin_firmware_check_display')")
2022-01-20 20:26:14,256 - octoprint.server - INFO - Added new permission from plugin logging: PLUGIN_LOGGING_MANAGE (needs: "Need(method='role', value='plugin_logging_manage')")
2022-01-20 20:26:14,257 - octoprint.server - INFO - Added new permission from plugin pi_support: PLUGIN_PI_SUPPORT_STATUS (needs: "Need(method='role', value='plugin_pi_support_check')")
2022-01-20 20:26:14,257 - octoprint.server - INFO - Added new permission from plugin pluginmanager: PLUGIN_PLUGINMANAGER_MANAGE (needs: "Need(method='role', value='plugin_pluginmanager_manage')")
2022-01-20 20:26:14,257 - octoprint.server - INFO - Added new permission from plugin pluginmanager: PLUGIN_PLUGINMANAGER_INSTALL (needs: "Need(method='role', value='plugin_pluginmanager_manage'), Need(method='role', value='plugin_pluginmanager_install')")
2022-01-20 20:26:14,263 - octoprint.server - INFO - Added new permission from plugin softwareupdate: PLUGIN_SOFTWAREUPDATE_CHECK (needs: "Need(method='role', value='plugin_softwareupdate_check')")
2022-01-20 20:26:14,264 - octoprint.server - INFO - Added new permission from plugin softwareupdate: PLUGIN_SOFTWAREUPDATE_UPDATE (needs: "Need(method='role', value='plugin_softwareupdate_update')")
2022-01-20 20:26:14,265 - octoprint.server - INFO - Added new permission from plugin softwareupdate: PLUGIN_SOFTWAREUPDATE_CONFIGURE (needs: "Need(method='role', value='plugin_softwareupdate_configure')")
2022-01-20 20:26:15,464 - octoprint.util.pip - INFO - Using "/home/pi/oprint/bin/python3 -m pip" as command to invoke pip
2022-01-20 20:26:16,357 - octoprint.util.pip - INFO - Version of pip is 20.3.3
2022-01-20 20:26:16,360 - octoprint.util.pip - INFO - pip installs to /home/pi/oprint/lib/python3.7/site-packages (writable -> yes), --user flag needed -> no, virtual env -> yes
2022-01-20 20:26:16,361 - octoprint.util.pip - INFO - ==> pip ok -> yes
2022-01-20 20:26:16,462 - octoprint.plugins.softwareupdate - INFO - Loaded version cache from disk
2022-01-20 20:26:16,487 - octoprint.plugins.softwareupdate - INFO - Loaded update log from disk
2022-01-20 20:26:16,535 - octoprint.plugin.core - INFO - Initialized 18 plugin implementation(s)
2022-01-20 20:26:16,547 - octoprint.plugin.core - INFO - 19 plugin(s) registered with the system:
|  Action Command Notification Support (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/action_command_notification
|  Action Command Prompt Support (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/action_command_prompt
|  Announcement Plugin (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/announcements
|  Anonymous Usage Tracking (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/tracking
|  Application Keys Plugin (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/appkeys
|  Backup & Restore (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/backup
|  Better Grbl Support (2.1.3) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_bettergrblsupport
|  Core Wizard (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/corewizard
|  Discovery (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/discovery
|  Error Tracking (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/errortracking
|  Event Manager (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/eventmanager
|  File Check (2021.2.23) (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_file_check
|  Firmware Check (2021.10.11) (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_firmware_check
| !GCode Viewer (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/gcodeviewer
|  Logging (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/logging
|  Pi Support Plugin (2021.10.28) (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_pi_support
|  Plugin Manager (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/pluginmanager
|  Software Update (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/softwareupdate
|  Virtual Printer (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/virtual_printer
Prefix legend: ! = disabled, # = blacklisted, * = incompatible
2022-01-20 20:26:16,582 - octoprint.environment - INFO - Detected environment is Python 3.7.3 under Linux (linux). Details:
|  hardware:
|    cores: 4
|    freq: 1400.0
|    ram: 914006016
|  os:
|    bits: 32
|    id: linux
|    platform: linux
|  plugins:
|    pi_support:
|      model: Raspberry Pi 3 Model B Plus Rev 1.3
|      octopi_version: 0.18.0
|      throttle_state: '0x0'
|  python:
|    pip: 20.3.3
|    version: 3.7.3
|    virtualenv: /home/pi/oprint
2022-01-20 20:26:16,596 - octoprint.server - INFO - Reset webasset folder /home/pi/.octoprint/generated/webassets...
2022-01-20 20:26:16,616 - octoprint.server - INFO - Reset webasset folder /home/pi/.octoprint/generated/.webassets-cache...
2022-01-20 20:26:17,451 - octoprint.server - INFO - Shutting down intermediary server...
2022-01-20 20:26:17,455 - octoprint.server - INFO - Intermediary server shut down
2022-01-20 20:26:17,458 - octoprint.events - INFO - Processing startup event, this is our first event
2022-01-20 20:26:17,459 - octoprint.events - INFO - Adding 2 events to queue that were held back before startup event
2022-01-20 20:26:17,461 - octoprint.filemanager - INFO - Adding backlog items from all storage types to analysis queue...
2022-01-20 20:26:17,472 - octoprint.server - INFO - Autoconnect on startup is configured, trying to connect to the printer...
2022-01-20 20:26:17,496 - octoprint.plugins.softwareupdate - INFO - Fetching check overlays from https://plugins.octoprint.org/update_check_overlay.json
2022-01-20 20:26:17,542 - octoprint.filemanager - INFO - Added 0 items from storage type "local" to analysis queue
2022-01-20 20:26:17,549 - octoprint.plugins.pluginmanager - INFO - Loaded plugin repository data from disk, was still valid
2022-01-20 20:26:18,974 - octoprint.server - INFO - Trying to connect to configured serial port /dev/ttyUSB0
2022-01-20 20:26:19,134 - octoprint.util.comm - INFO - Changing monitoring state from "Offline" to "Detecting serial connection"
2022-01-20 20:26:19,136 - octoprint.util.comm - INFO - Serial detection: Performing autodetection with 7 port/baudrate candidates: /dev/ttyUSB0@115200, /dev/ttyUSB0@250000, /dev/ttyUSB0@230400, /dev/ttyUSB0@57600, /dev/ttyUSB0@38400, /dev/ttyUSB0@19200, /dev/ttyUSB0@9600
2022-01-20 20:26:19,136 - octoprint.util.comm - INFO - Serial detection: Trying port /dev/ttyUSB0, baudrate 115200
2022-01-20 20:26:19,137 - octoprint.util.comm - INFO - Connecting to port /dev/ttyUSB0, baudrate 115200
2022-01-20 20:26:19,222 - octoprint.server.util.watchdog - INFO - Running initial scan on watched folder...
2022-01-20 20:26:19,267 - octoprint.server.util.watchdog - INFO - ... initial scan done.
2022-01-20 20:26:19,332 - octoprint.util.comm - INFO - Serial detection: Handshake attempt #1 with timeout 2.0s
2022-01-20 20:26:19,335 - zeroconf - WARNING - Error with socket 5 (('10.0.10.1', 5353))): [Errno 126] Required key not available
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 987, in sendto
    self._sock.sendto(data, addr)
OSError: [Errno 126] Required key not available
2022-01-20 20:26:20,249 - octoprint.plugins.discovery - INFO - Registered 'OctoPrint instance on octopi._http._tcp.local.' for _http._tcp.local.
2022-01-20 20:26:20,536 - octoprint.plugins.pluginmanager - INFO - Loaded notice data from disk, was still valid
2022-01-20 20:26:21,101 - octoprint.plugins.discovery - INFO - Registered 'OctoPrint instance on octopi._octoprint._tcp.local.' for _octoprint._tcp.local.
2022-01-20 20:26:21,119 - octoprint.plugins.discovery - INFO - Registered OctoPrint instance on octopi for SSDP
2022-01-20 20:26:21,146 - octoprint.server - INFO - Listening on http://127.0.0.1:5000
2022-01-20 20:26:21,243 - octoprint.plugins.pluginmanager - INFO - Loaded plugin repository data from disk, was still valid
2022-01-20 20:26:21,345 - octoprint.server.util.sockjs - INFO - New connection from client: ::ffff:10.0.0.160
2022-01-20 20:26:21,352 - octoprint.util.comm - INFO - Serial detection: Handshake attempt #2 with timeout 2.0s
2022-01-20 20:26:21,708 - octoprint.server.util.flask - INFO - Passively logging in user buriot from ::ffff:10.0.0.160
2022-01-20 20:26:21,719 - octoprint.access.users - INFO - Logged in user: buriot
2022-01-20 20:26:21,814 - octoprint.server.util.sockjs - INFO - User buriot logged in on the socket from client ::ffff:10.0.0.160
2022-01-20 20:26:22,337 - octoprint.util.pip - INFO - Using "/home/pi/oprint/bin/python3 -m pip" as command to invoke pip
2022-01-20 20:26:22,345 - octoprint.util.pip - INFO - pip installs to /home/pi/oprint/lib/python3.7/site-packages (writable -> yes), --user flag needed -> no, virtual env -> yes
2022-01-20 20:26:22,371 - octoprint.util.pip - INFO - ==> pip ok -> yes
2022-01-20 20:26:22,456 - octoprint.plugins.softwareupdate - INFO - Minimum free storage across all update relevant locations is 52.7GB. That is considered sufficient for updating.
2022-01-20 20:26:23,409 - octoprint.util.comm - INFO - Serial detection: Handshake attempt #3 with timeout 2.0s
2022-01-20 20:26:23,821 - octoprint.server.preemptive_cache - INFO - Preemptively caching / (ui _default) for {'base_url': 'http://octopi.local/', 'path': '/', 'query_string': 'l10n=en'}
2022-01-20 20:26:24,004 - octoprint.plugins.pluginmanager - INFO - Loaded notice data from disk, was still valid
2022-01-20 20:26:25,418 - octoprint.server.util.flask - INFO - Passively logging in user buriot from fe80::88f:2614:7a65:5cad
2022-01-20 20:26:25,419 - octoprint.access.users - INFO - Logged in user: buriot
2022-01-20 20:26:25,427 - octoprint.util.comm - INFO - Serial detection: Trying port /dev/ttyUSB0, baudrate 250000
2022-01-20 20:26:25,434 - octoprint.util.comm - INFO - Serial detection: Handshake attempt #1 with timeout 2.0s
2022-01-20 20:26:27,445 - octoprint.util.comm - INFO - Serial detection: Handshake attempt #2 with timeout 2.0s
2022-01-20 20:26:29,483 - octoprint.util.comm - INFO - Serial detection: Handshake attempt #3 with timeout 2.0s
2022-01-20 20:26:31,488 - octoprint.util.comm - INFO - Serial detection: Trying port /dev/ttyUSB0, baudrate 230400
2022-01-20 20:26:31,490 - octoprint.util.comm - INFO - Serial detection: Handshake attempt #1 with timeout 2.0s
2022-01-20 20:26:33,503 - octoprint.util.comm - INFO - Serial detection: Handshake attempt #2 with timeout 2.0s
2022-01-20 20:26:47,434 - octoprint.util.comm - INFO - Serial detection: Handshake attempt #3 with timeout 2.0s
2022-01-20 20:26:49,444 - octoprint.util.comm - INFO - Serial detection: Trying port /dev/ttyUSB0, baudrate 57600
2022-01-20 20:26:49,445 - octoprint.util.comm - INFO - Serial detection: Handshake attempt #1 with timeout 2.0s
2022-01-20 20:26:51,457 - octoprint.util.comm - INFO - Serial detection: Handshake attempt #2 with timeout 2.0s
2022-01-20 20:26:53,468 - octoprint.util.comm - INFO - Serial detection: Handshake attempt #3 with timeout 2.0s
2022-01-20 20:26:55,475 - octoprint.util.comm - INFO - Serial detection: Trying port /dev/ttyUSB0, baudrate 38400
2022-01-20 20:26:55,476 - octoprint.util.comm - INFO - Serial detection: Handshake attempt #1 with timeout 2.0s
2022-01-20 20:26:55,852 - octoprint.server.preemptive_cache - INFO - ... done in 20.10s
2022-01-20 20:26:55,853 - octoprint.server.preemptive_cache - INFO - Preemptively caching / (ui _default) for {'base_url': 'http://10.0.0.136/', 'path': '/', 'query_string': 'l10n=en'}
2022-01-20 20:26:55,880 - octoprint.server.util.sockjs - INFO - Client connection closed: ::ffff:10.0.0.160
2022-01-20 20:26:56,847 - octoprint.server.util.flask - INFO - Passively logging in user buriot from ::ffff:10.0.0.160
2022-01-20 20:26:56,848 - octoprint.access.users - INFO - Logged in user: buriot
2022-01-20 20:26:56,993 - octoprint.server.preemptive_cache - INFO - ... done in 1.14s
2022-01-20 20:26:57,489 - octoprint.util.comm - INFO - Serial detection: Handshake attempt #2 with timeout 2.0s
2022-01-20 20:26:59,494 - octoprint.util.comm - INFO - Serial detection: Handshake attempt #3 with timeout 2.0s
2022-01-20 20:26:59,873 - octoprint.server.util.sockjs - INFO - New connection from client: ::ffff:10.0.0.160
2022-01-20 20:26:59,998 - octoprint.server.util.flask - INFO - Passively logging in user buriot from ::ffff:10.0.0.160
2022-01-20 20:26:59,998 - octoprint.access.users - INFO - Logged in user: buriot
2022-01-20 20:27:01,500 - octoprint.util.comm - INFO - Serial detection: Trying port /dev/ttyUSB0, baudrate 19200
2022-01-20 20:27:01,503 - octoprint.util.comm - INFO - Serial detection: Handshake attempt #1 with timeout 2.0s
2022-01-20 20:27:02,194 - octoprint.server.util.sockjs - INFO - User buriot logged in on the socket from client ::ffff:10.0.0.160
2022-01-20 20:27:03,510 - octoprint.util.comm - INFO - Serial detection: Handshake attempt #2 with timeout 2.0s
2022-01-20 20:27:05,524 - octoprint.util.comm - INFO - Serial detection: Handshake attempt #3 with timeout 2.0s
2022-01-20 20:27:07,535 - octoprint.util.comm - INFO - Serial detection: Trying port /dev/ttyUSB0, baudrate 9600
2022-01-20 20:27:07,536 - octoprint.util.comm - INFO - Serial detection: Handshake attempt #1 with timeout 2.0s
2022-01-20 20:27:09,541 - octoprint.util.comm - INFO - Serial detection: Handshake attempt #2 with timeout 2.0s
2022-01-20 20:27:11,545 - octoprint.util.comm - INFO - Serial detection: Handshake attempt #3 with timeout 2.0s
2022-01-20 20:27:13,549 - octoprint.util.comm - INFO - Changing monitoring state from "Detecting serial connection" to "Error"
2022-01-20 20:27:13,561 - octoprint.util.comm - INFO - Changing monitoring state from "Error" to "Offline after error"
2022-01-20 20:27:13,567 - octoprint.plugins.action_command_notification - INFO - Notifications cleared
2022-01-20 20:27:35,709 - octoprint.server.util.sockjs - INFO - Client connection closed: ::ffff:10.0.0.160
`

**Comment by synman** [comment] 2022-01-20 23:16
I deciphered your wall of text there.... nothing to glean from it.  I would be nice if you could just upload the file, or at the least parse it with proper carriage return / line feeds.   My eyes still hurt.

Let's set the logging level for the plugin to debug and try again.  

<img width="910" alt="Screen Shot 2022-01-20 at 6 15 55 PM" src="https://user-images.githubusercontent.com/1299716/150437209-0749b6b7-ce6c-4e3f-a4a5-62ee3140fd00.png">

**Comment by synman** [comment] 2022-01-20 23:30
you can find the above in Settings --> Octoprint --> Logging

**Comment by mbt45** [comment] 2022-01-21 11:11
Sorry for the wall of text, I couldn't find a way to attach files, but I got it now
[octoprint(6).log](https://github.com/synman/Octoprint-Bettergrblsupport/files/7912789/octoprint.6.log)
.

**Comment by synman** [comment] 2022-01-21 14:44
According to the log (assuming your printer is connected to ttyUSB0 @ 115200) this error is happening at an OS level when BGS tries to inject the initial handshake.  Behind the scenes I replace the M110 with a ?.

```
2022-01-21 11:08:42,122 - octoprint.util.comm - INFO - Serial detection: Trying port /dev/ttyUSB0, baudrate 115200
2022-01-21 11:08:42,122 - octoprint.util.comm - INFO - Connecting to port /dev/ttyUSB0, baudrate 115200
2022-01-21 11:08:42,132 - octoprint.plugins.bettergrblsupport - DEBUG - __init__: on_event event=[PrinterStateChanged] payload=[{'state_id': 'DETECT_SERIAL', 'state_string': 'Detecting serial connection'}]
2022-01-21 11:08:42,166 - octoprint.server.util.watchdog - INFO - Running initial scan on watched folder...
2022-01-21 11:08:42,211 - octoprint.server.util.watchdog - INFO - ... initial scan done.
2022-01-21 11:08:42,243 - octoprint.util.comm - INFO - Serial detection: Handshake attempt #1 with timeout 2.0s
2022-01-21 11:08:42,270 - octoprint.plugins.bettergrblsupport - DEBUG - __init__: hook_gcode_sending phase=[sending] cmd=[M110 N0] cmd_type=[None] gcode=[M110]
2022-01-21 11:08:42,271 - octoprint.plugins.bettergrblsupport - DEBUG - Ignoring M110 N0
2022-01-21 11:08:42,309 - zeroconf - WARNING - Error with socket 5 (('10.0.10.1', 5353))): [Errno 126] Required key not available
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 987, in sendto
    self._sock.sendto(data, addr)
OSError: [Errno 126] Required key not available
```

I'll do a little bit of research into what error 126 is.  It is happening at an intrinsic level so I'm a bit curious as to what is going on.

Please confirm your machine is connected to ttyUSB0 (it likely is).   As I'm researching this, if you could also disable auto detection, set your com port and baud to ttyUSB0 / 115200, try again, and send me the log snippet that would be awesome.

**Comment by synman** [comment] 2022-01-21 15:03
I think this more accurately captures what is happening specific to auto detection.  I've ruled out the zeroconf 129 error as root cause... that's mdns like I thought, unrelated to auto negotiation of a USB connection.

```
2022-01-21 11:08:42,122 - octoprint.util.comm - INFO - Serial detection: Trying port /dev/ttyUSB0, baudrate 115200
2022-01-21 11:08:42,122 - octoprint.util.comm - INFO - Connecting to port /dev/ttyUSB0, baudrate 115200
2022-01-21 11:08:42,132 - octoprint.plugins.bettergrblsupport - DEBUG - __init__: on_event event=[PrinterStateChanged] payload=[{'state_id': 'DETECT_SERIAL', 'state_string': 'Detecting serial connection'}]
2022-01-21 11:08:42,243 - octoprint.util.comm - INFO - Serial detection: Handshake attempt #1 with timeout 2.0s
2022-01-21 11:08:42,270 - octoprint.plugins.bettergrblsupport - DEBUG - __init__: hook_gcode_sending phase=[sending] cmd=[M110 N0] cmd_type=[None] gcode=[M110]
2022-01-21 11:08:42,271 - octoprint.plugins.bettergrblsupport - DEBUG - Ignoring M110 N0
2022-01-21 11:08:44,268 - octoprint.plugins.bettergrblsupport - DEBUG - __init__: hook_gcode_received line=[]
2022-01-21 11:08:44,321 - octoprint.util.comm - INFO - Serial detection: Handshake attempt #2 with timeout 2.0s
2022-01-21 11:08:44,336 - octoprint.plugins.bettergrblsupport - DEBUG - __init__: hook_gcode_sending phase=[sending] cmd=[M110 N0] cmd_type=[None] gcode=[M110]
2022-01-21 11:08:44,337 - octoprint.plugins.bettergrblsupport - DEBUG - Ignoring M110 N0
2022-01-21 11:08:46,331 - octoprint.plugins.bettergrblsupport - DEBUG - __init__: hook_gcode_received line=[]
2022-01-21 11:08:46,347 - octoprint.util.comm - INFO - Serial detection: Handshake attempt #3 with timeout 2.0s
2022-01-21 11:08:46,363 - octoprint.plugins.bettergrblsupport - DEBUG - __init__: hook_gcode_sending phase=[sending] cmd=[M110 N0] cmd_type=[None] gcode=[M110]
2022-01-21 11:08:46,365 - octoprint.plugins.bettergrblsupport - DEBUG - Ignoring M110 N0
```
Your machine is responding with a blank response, that's what this is:

2022-01-21 11:08:44,268 - octoprint.plugins.bettergrblsupport - DEBUG - __init__: hook_gcode_received line=[]

I may have changed some code to ignore blank / empty responses.  I'm curious if this empty response is your machine's way of saying, "hey, I'm here".

What is the specific manufacturer / brand / model of your machine?

**Comment by synman** [comment] 2022-01-21 15:18
Here's the gcode sending handling logic I had prior to "cleaning" things up in 2.1.0:
```
        # suppress reset line #s
        if self.suppressM110 and cmd.upper().startswith('M110'):
            self._logger.debug('Ignoring %s', cmd)
            return ("$I", )
```
and here it is in 2.1.0+:
```
        if self.suppressM110 and cmd.upper().startswith('M110'):
            self._logger.debug('Ignoring %s', cmd)
            return ("?", )
```

I'm thinking through how I want to accommodate this for you.  My gut tells me if I return a $ command like $I (grbl version info) you'll be back in business.

**Comment by synman** [comment] 2022-01-21 19:14
@mbt45 I think I have a fix for this but would like to do some validation before elevating it the release candidate channel.  Are you up for trying the dev channel?  If so, I'll push a commit to GitHub and we can see if it solves your problem.

https://github.com/synman/Octoprint-Bettergrblsupport/wiki/Bleeding-Edge-Updates

**Comment by synman** [comment] 2022-01-21 19:23
opening this back up pending confirmation of resolution

**Comment by mbt45** [comment] 2022-01-21 20:30
I am updating. I'll let you know the result ASAP

**Comment by mbt45** [comment] 2022-01-21 20:34
Ok it solved the issue
Thank  you

**Comment by synman** [comment] 2022-01-21 22:14
also, thanks for getting me the data I needed to get to the bottom of it.  Be sure set your logging level back to INFO too.  BGS can generate some decent log data at DEBUG level.

**Comment by mbt45** [comment] 2022-01-21 22:50
Hi
I think I talked too fast.

Although it is saying connected it seem the controls don't work. And I am getting a lot of " Send: ?" in the console

Send: ?

**Comment by mbt45** [comment] 2022-01-21 22:51
[octoprint(8).log](https://github.com/synman/Octoprint-Bettergrblsupport/files/7917013/octoprint.8.log)

**Comment by mbt45** [comment] 2022-01-22 01:04
Port ttyUSB0
Autodetection  off
Model NEJE Master 2S.
Before last update I had no problem engraving with octopi better grlb

I'll be able to try Lightbrun tomorrow only.

I tried soft reset but no response
I tried $$ but not response.


It is getting pretty late here so I'll be able to see your next message tomorrow only.

Thank you again for your help

**Comment by synman** [comment] 2022-01-22 01:52
Opening this back up.  Am hopeful seeing your lightburn console output will shed some light on this.

**Comment by synman** [comment] 2022-01-22 07:02
@mbt45 I pushed out a new update to the dev channel tonight that initializes the connection with two linefeeds.  I was looking over code from other open source grbl gcode senders and this seems to be a predominant pattern.

I had to fake out Octoprint to make it work.  Octoprint intentionally filters out "blank" commands but I came up with a creative work around that consistently generates the Grbl welcome message on my two machines.

Let me know how it goes.

**Comment by mbt45** [comment] 2022-01-22 23:44
Here is the console of lightburn.

I am now reinstalling a fresh new octopi session and will download the plugin
<img width="735" alt="Screenshot 2022-01-22 at 20 39 59" src="https://user-images.githubusercontent.com/44694015/150659045-6c3503da-3e01-4495-af4a-feba9b6b257b.png">
 soon.

**Comment by synman** [comment] 2022-01-22 23:46
yeah, I fired up Lightburn last nigh as well and noted it doesn't share anything about its negotiation phase.  Before you rebuild octopi, the latest dev build of bgs.

**Comment by mbt45** [comment] 2022-01-23 11:47
Hi the last update seem to work. 

Strangely I setup a fresh new instance of octopi on a new SD card with your "stable" release of Better GRLB and it worked. I am now a little baffled. Was it is your plugin that was in cause or a conflict between an old octopi and your plugin during upgrade.

Never the less your stable release works on a fresh octopi, as well as your 4fcd97d022db261ea343293325f9b4d8dbeed603
Maybe just a warning to reinstall octopi in case they someone else the same issue as I did would be sufficient.


Thank you for your invaluable help and work.
Is there a place I can pay you a coffee ;) ?

**Comment by synman** [comment] 2022-01-23 15:00
I should have asked for a copy of your config.yaml.

You are the second person to have a weird condition that was resolved with a rebuild. 
 

One gent had a phantom M876 firing out of nowhere.  

I would've loved to have known if my /n/n fix would have made a difference here.

**Closed** 2022-01-23 15:01 UTC
Labels: bug
